# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(272, 343)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SubmitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(40, 230, 191, 31))
        self.SubmitButton.setObjectName("SubmitButton")
        self.StudentLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.StudentLabel.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.StudentLabel.setObjectName("StudentLabel")
        self.AttemptsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.AttemptsLabel.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.AttemptsLabel.setObjectName("AttemptsLabel")
        self.StudentBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.StudentBox.setGeometry(QtCore.QRect(100, 10, 101, 21))
        self.StudentBox.setObjectName("StudentBox")
        self.AttemptsBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.AttemptsBox.setGeometry(QtCore.QRect(100, 50, 101, 21))
        self.AttemptsBox.setObjectName("AttemptsBox")
        self.SubmitLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.SubmitLabel.setGeometry(QtCore.QRect(30, 270, 201, 20))
        self.SubmitLabel.setObjectName("SubmitLabel")
        self.ScoreLabel1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.ScoreLabel1.setGeometry(QtCore.QRect(50, 90, 91, 16))
        self.ScoreLabel1.setObjectName("ScoreLabel1")
        self.ScoreLabel2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.ScoreLabel2.setGeometry(QtCore.QRect(50, 120, 91, 16))
        self.ScoreLabel2.setObjectName("ScoreLabel2")
        self.ScoreLabel3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.ScoreLabel3.setGeometry(QtCore.QRect(50, 150, 91, 16))
        self.ScoreLabel3.setObjectName("ScoreLabel3")
        self.ScoreLabel4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.ScoreLabel4.setGeometry(QtCore.QRect(50, 180, 91, 16))
        self.ScoreLabel4.setObjectName("ScoreLabel4")
        self.ScoreBox1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ScoreBox1.setGeometry(QtCore.QRect(100, 90, 101, 21))
        self.ScoreBox1.setObjectName("ScoreBox1")
        self.ScoreBox2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ScoreBox2.setGeometry(QtCore.QRect(100, 120, 101, 21))
        self.ScoreBox2.setObjectName("ScoreBox2")
        self.ScoreBox3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ScoreBox3.setGeometry(QtCore.QRect(100, 150, 101, 21))
        self.ScoreBox3.setObjectName("ScoreBox3")
        self.ScoreBox4 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ScoreBox4.setGeometry(QtCore.QRect(100, 180, 101, 21))
        self.ScoreBox4.setObjectName("ScoreBox4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 272, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("GradesApp", "GradesApp"))
        self.SubmitButton.setText(_translate("MainWindow", "SUBMIT"))
        self.StudentLabel.setText(_translate("MainWindow", "Student name:"))
        self.AttemptsLabel.setText(_translate("MainWindow", "No of attempts:"))
        self.SubmitLabel.setText(_translate("MainWindow", "                           Submitted"))
        self.ScoreLabel1.setText(_translate("MainWindow", "Score 1:"))
        self.ScoreLabel2.setText(_translate("MainWindow", "Score 2:"))
        self.ScoreLabel3.setText(_translate("MainWindow", "Score 3:"))
        self.ScoreLabel4.setText(_translate("MainWindow", "Score 4:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
